import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google"; // Geist o'rniga Inter
import styles from "@/styles/Home.module.css";

// Next.js 14 uchun standart shrift sozlamasi
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Nestar Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      
      {/* Layout o'zgarmasligi uchun styles.page va inter shriftini birga beramiz */}
      <div className={`${styles.page} ${inter.className}`}>
        <main className={styles.main}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js logo"
            width={100}
            height={20}
            priority
          />
          
          <div className={styles.intro}>
            <h1 style={{ fontSize: '3rem', marginBottom: '10px' }}>PAGES ROUTER</h1>
            <h2 style={{ fontSize: '1.5rem', opacity: 0.8 }}>
              To get started, edit the index.tsx file.
            </h2>
            <p>
              Looking for a starting point or more instructions? Head over to{" "}
              <a
                href="https://nextjs.org/docs"
                target="_blank"
                rel="noopener noreferrer"
              >
                Documentation
              </a>.
            </p>
          </div>

          <div className={styles.ctas}>
            <a
              className={styles.primary}
              href="https://vercel.com/new"
              target="_blank"
              rel="noopener noreferrer"
            >
              <Image
                src="/vercel.svg"
                alt="Vercel logo"
                width={16}
                height={16}
                style={{ marginRight: '8px' }}
              />
              Deploy Now
            </a>
            <a
              className={styles.secondary}
              href="https://nextjs.org/docs"
              target="_blank"
              rel="noopener noreferrer"
            >
              Read Docs
            </a>
          </div>
        </main>
      </div>
    </>
  );
}